version: '3.4'

services:
  app:
    command: sleep infinity

    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 3.1-bullseye
        NODE_VERSION: lts/*

    volumes:
      - ../..:/workspaces:cached

    networks:
      - db-server
    ports:
      - '49152:49152'

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # The next line runs scripts during DB init only; more here:
      # - https://hub.docker.com/_/postgres/#:~:text=POSTGRES_USER%2C%20and%20POSTGRES_DB.-,initialization%20scripts,-If%20you%20would
      # - https://stackoverflow.com/questions/26598738/how-to-create-user-database-in-script-for-docker-postgres
      - ./create-db-user.sql:/docker-entrypoint-initdb.d/create-db-user.sql
    networks:
      - db-server
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      # Your config/database.yml should use the user and password you set here,
      # and host "db" (as that's the name of this service). You can use whatever
      # database name you want. Use `bin/rails db:prepare` to create the database.
      #
      # Example:
      #
      #  development:
      #    <<: *default
      #    host: db
      #    username: postgres
      #    password: postgres
      #    database: myapp_development

      # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
      # (Adding the "ports" property to this file will not forward from a Codespace.)

networks:
  db-server:


volumes:
  postgres-data:
