version: '3.4'

services:
  ruby-container:
    image: ruby-container

    command: sleep infinity

    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 3.1-bullseye
        NODE_VERSION: lts/*

    volumes:
      - ../..:/workspaces:cached

    networks:
      - plantuml-server
    ports:
      - '49152:49152'

  plantuml-container:
    image: 'plantuml/plantuml-server:jetty'
    networks:
      plantuml-server:
        aliases:
          - plantuml
    ports:
      - '8080'

networks:
  plantuml-server:
